name: docker push
on:
  create:
  push:
    branches:
      - main

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - uses: fsouza/docker-publish-action@v1.0.1
        if: github.event.ref_type == 'tag' || github.event_name == 'push'
        with:
          docker-image: fsouza/docker-ssl-proxy
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
