name: docker push
on:
  push:
    branches:
      - master

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0

      - name: build and push
        uses: elgohr/Publish-Docker-Github-Action@1.8
        with:
          name: fsouza/docker-ssl-proxy
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
